# Logback config file path
logging:
  config: classpath:logback-spring-dev.xml


spring:
  ## PostgreSQL
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/quote_service
    username: quote_admin
  ## Liquibase
  liquibase:
    change-log: classpath:db/changelog/index.xml